services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      UNIFI_IP: '192.168.2.1'
      UNIFI_PORT: 443
      UNIFI_USERNAME: 'admin'
      UNIFI_PASSWORD: 'password'
      UNIFI_SITE_ID: 'default'
      UNIFI_SSID: ''
      UNIFI_SSID_PASSWORD: ''
      AUTH_INTERNAL_ENABLED: 'true'
      AUTH_INTERNAL_PASSWORD: '0000'
      AUTH_INTERNAL_BEARER_TOKEN: '00000000-0000-0000-0000-000000000000'
      AUTH_OIDC_ENABLED: 'false'
      AUTH_OIDC_ISSUER_BASE_URL: ''
      AUTH_OIDC_APP_BASE_URL: ''
      AUTH_OIDC_CLIENT_ID: ''
      AUTH_OIDC_CLIENT_SECRET: ''
      AUTH_DISABLE: 'false'
      VOUCHER_TYPES: '480,1,,,;'
      VOUCHER_CUSTOM: 'true'
      SERVICE_WEB: 'true'
      SERVICE_API: 'false'
      PRINTERS: 'pdf'
      PAPER_SIZE: 'A6'
      SMTP_FROM: ''
      SMTP_HOST: ''
      SMTP_PORT: ''
      SMTP_SECURE: ''
      SMTP_USERNAME: ''
      SMTP_PASSWORD: ''
      KIOSK_ENABLED: 'false'
      KIOSK_VOUCHER_TYPE: '480,1,,,'
      LOG_LEVEL: 'info'
      TRANSLATION_DEBUG: 'false'
